### ISSUE TITLE
White screen of death in 2.8.1

### ISSUE THREAD

**Issue by nathanpitman** [rsanchez/filter_by_author#1]
In 2.8.1 and maybe earlier (haven't checked) I get the white screen of death when trying to access the edit screen after installing the extension. Turning on debug in admin.php reveals the following PHP error:

`
Fatal error: Call to undefined method EE_Javascript::generate_json() in /Users/Shared/Sites/broadcast-bridge/dev/third_party/filter_by_author/ext.filter_by_author.php on line 151
`

:)

**Comment by nathanpitman** [comment]
Ah, so it looks like this might be related to https://support.ellislab.com/bugs/detail/20386/javascript-error-after-upgrade-to-ee-2.8.1

**Comment by rsanchez** [comment]
Download the latest, should work.

**Comment by nathanpitman** [comment]
Brill, thanks Rob. :)
